tagFormat: '${version}'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - 'semantic-release-mnpm'
  # - '@semantic-release/github'
  - - '@semantic-release/git'
    - message: "chore: Release 🚀 ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets:
        - 'CHANGELOG.md'
        - '*.lock'
        - - '**/package.json'
          - '!**/node_modules/**/package.json'
branches:
  - test-release
  - test
